import { Product, Customer, Category, LoanEligible } from './types';

export const products: Product[] = [
  {
    id: 100,
    name: 'Shampoo',
    price: 399,
    rating: 4.0,
    category: Category.cosmetics,
    stock: 10,
    discount: 10,
  },
  {
    id: 101,
    name: 'Lip Stick',
    price: 189,
    rating: 4.1,
    category: Category.cosmetics,
    stock: 23,
    discount: 5,
  },
  {
    id: 102,
    name: 'Eye Linear',
    price: 90,
    rating: 4.5,
    category: Category.cosmetics,
    stock: 9,
    discount: 0,
  },
  {
    id: 103,
    name: 'Laptop',
    price: 43200,
    rating: 3.9,
    category: Category.electronic,
    stock: 15,
    discount: 15,
  },
  {
    id: 104,
    name: 'Mobile',
    price: 4500,
    rating: 4.2,
    category: Category.electronic,
    stock: 20,
    discount: 8,
  },
  {
    id: 105,
    name: 'Trimmer',
    price: 1100,
    rating: 4.8,
    category: Category.electronic,
    stock: 8,
    discount: 12,
  },
  {
    id: 106,
    name: 'The Great Gatsby',
    price: 299,
    rating: 4.6,
    category: Category.book,
    stock: 25,
    discount: 20,
  },
  {
    id: 107,
    name: 'To Kill a Mockingbird',
    price: 349,
    rating: 4.7,
    category: Category.book,
    stock: 18,
    discount: 10,
  },
  {
    id: 108,
    name: '1984',
    price: 279,
    rating: 4.5,
    category: Category.book,
    stock: 22,
    discount: 0,
  },
  {
    id: 109,
    name: 'Organic Rice',
    price: 450,
    rating: 4.3,
    category: Category.grocery,
    stock: 50,
    discount: 5,
  },
  {
    id: 110,
    name: 'Whole Wheat Bread',
    price: 80,
    rating: 4.4,
    category: Category.grocery,
    stock: 35,
    discount: 3,
  },
  {
    id: 111,
    name: 'Almond Butter',
    price: 520,
    rating: 4.6,
    category: Category.grocery,
    stock: 12,
    discount: 7,
  },
];

export const customer: Customer[] = [
  {
    id: 100,
    name: 'Santosh',
    phone: 9889889880,
    Address: 'Raghav Nagar Deoria',
    loan: LoanEligible.nonEligible,
  },
  {
    id: 101,
    name: 'Priya Sharma',
    phone: 8765432109,
    Address: 'MG Road Bangalore',
    loan: LoanEligible.eligible,
  },
  {
    id: 102,
    name: 'Rajesh Kumar',
    phone: 9123456789,
    Address: 'CP Delhi',
    loan: LoanEligible.nonEligible,
  },
  {
    id: 103,
    name: 'Anjali Singh',
    phone: 9876543210,
    Address: 'Bandra Mumbai',
    loan: LoanEligible.eligible,
  },
  {
    id: 104,
    name: 'Vikram Patel',
    phone: 9234567890,
    Address: 'SG Highway Ahmedabad',
    loan: LoanEligible.eligible,
  },
  {
    id: 105,
    name: 'Neha Gupta',
    phone: 9345678901,
    Address: 'Salt Lake Kolkata',
    loan: LoanEligible.nonEligible,
  },
  {
    id: 106,
    name: 'Arjun Nair',
    phone: 9456789012,
    Address: 'Indiranagar Bangalore',
    loan: LoanEligible.eligible,
  },
  {
    id: 107,
    name: 'Divya Reddy',
    phone: 9567890123,
    Address: 'Hitech City Hyderabad',
    loan: LoanEligible.nonEligible,
  },
  {
    id: 108,
    name: 'Aditya Verma',
    phone: 9678901234,
    Address: 'Sector 15 Noida',
    loan: LoanEligible.eligible,
  },
  {
    id: 109,
    name: 'Riya Desai',
    phone: 9789012345,
    Address: 'Vile Parle Mumbai',
    loan: LoanEligible.eligible,
  },
  {
    id: 110,
    name: 'Sanjay Malik',
    phone: 9890123456,
    Address: 'Connaught Place Delhi',
    loan: LoanEligible.nonEligible,
  },
  {
    id: 111,
    name: 'Pooja Rao',
    phone: 9901234567,
    Address: 'Whitefield Bangalore',
    loan: LoanEligible.eligible,
  },
  {
    id: 112,
    name: 'Harsh Singh',
    phone: 9012345678,
    Address: 'Cyber Hub Gurgaon',
    loan: LoanEligible.nonEligible,
  },
];
