await page.getByRole('link', { name: ' Signup / Login' }).click();
await page.getByRole('textbox', { name: 'Name' }).click();
await page.getByRole('textbox', { name: 'Name' }).fill('Sachin Gupta');
await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').click();
await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').fill('sachin22@gmail.com');
await page.getByRole('button', { name: 'Signup' }).click();
await page.locator('form').filter({ hasText: 'Email Address already exist!' }).getByPlaceholder('Email Address').click();
await page.locator('form').filter({ hasText: 'Email Address already exist!' }).getByPlaceholder('Email Address').fill('sachin22@gmail.com');
await page.locator('form').filter({ hasText: 'Email Address already exist!' }).getByPlaceholder('Email Address').press('ArrowLeft');
await page.locator('form').filter({ hasText: 'Email Address already exist!' }).getByPlaceholder('Email Address').press('ArrowLeft');
await page.locator('form').filter({ hasText: 'Email Address already exist!' }).getByPlaceholder('Email Address').press('ArrowLeft');
await page.locator('form').filter({ hasText: 'Email Address already exist!' }).getByPlaceholder('Email Address').press('ArrowLeft');
await page.locator('form').filter({ hasText: 'Email Address already exist!' }).getByPlaceholder('Email Address').press('ArrowLeft');
await page.locator('form').filter({ hasText: 'Email Address already exist!' }).getByPlaceholder('Email Address').press('ArrowRight');
await page.locator('form').filter({ hasText: 'Email Address already exist!' }).getByPlaceholder('Email Address').press('ArrowRight');
await page.locator('form').filter({ hasText: 'Email Address already exist!' }).getByPlaceholder('Email Address').fill('sachin2234@gmail.com');
await page.getByRole('button', { name: 'Signup' }).click();
await page.getByRole('radio', { name: 'Mr.' }).check();
await page.getByRole('radio', { name: 'Mr.' }).click();
await page.getByRole('radio', { name: 'Mr.' }).press('1');
await page.getByRole('radio', { name: 'Mr.' }).press('2');
await page.getByRole('textbox', { name: 'Password *' }).click();
await page.getByRole('textbox', { name: 'Password *' }).fill('1234567890');
await page.locator('#days').selectOption('20');
await page.locator('#months').selectOption('12');
await page.locator('#years').selectOption('2003');
await page.getByRole('checkbox', { name: 'Sign up for our newsletter!' }).check();
await page.getByRole('checkbox', { name: 'Receive special offers from' }).check();
await page.getByRole('textbox', { name: 'First name *' }).click();
await page.getByRole('textbox', { name: 'First name *' }).fill('Sachin');
await page.getByRole('textbox', { name: 'Last name *' }).click();
await page.getByRole('textbox', { name: 'Last name *' }).fill('Gupta');
await page.getByRole('textbox', { name: 'Company', exact: true }).click();
await page.getByRole('textbox', { name: 'Company', exact: true }).fill('Typing Starter');
await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).click();
await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).fill('123,Full Name gulam tola');
await page.getByRole('textbox', { name: 'Address 2' }).click();
await page.getByRole('textbox', { name: 'Address 2' }).fill('tola');
await page.getByRole('textbox', { name: 'State *' }).click();
await page.getByRole('textbox', { name: 'State *' }).click();
await page.getByRole('textbox', { name: 'State *' }).fill('Uttar Pradesh');
await page.getByRole('textbox', { name: 'City * Zipcode *' }).click();
await page.getByRole('textbox', { name: 'City * Zipcode *' }).fill('Badadev');
await page.locator('#zipcode').click();
await page.locator('#zipcode').fill('274001');
await page.getByRole('textbox', { name: 'Mobile Number *' }).click();
await page.getByRole('textbox', { name: 'Mobile Number *' }).fill('123456789012');
await page.getByRole('button', { name: 'Create Account' }).click();
await page.getByRole('link', { name: 'Continue' }).click();